# Generated by Django 6.1 on 2026-09-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
